#!/usr/bin/env bash
#MISE description="Build the project"
#MISE depends=["setup"]
#MISE sources=["src/**/*"]
#MISE outputs=["dist/index.js", "dist/index.d.ts"]

rm -rf dist && bun build ./src/index.ts --outdir dist --target bun --external @ai-sdk/openai-compatible --external @opencode-ai/plugin --external @opencode-ai/sdk && tsc -p tsconfig.build.json
